import 'package:flutter/material.dart';

final users = [
  {
    "name": "Mohamed",
    "language": "arabic",
    "identifier": "dev",
    "password": "123",
  },
];

final accounts = [
  {
    "userId": 1,
    "name": "wallet",
    "type": "cash",
    "balance": 7500,
    "currency": "EGP",
    "isActive": 1,
  },
];

final cats = [
  // =========================
  // INCOME
  // =========================
  {
    'id': 1,
    'name': 'Salary',
    'type': 'income',
    'icon': Icons.payments.codePoint,
    'color': Colors.green.toARGB32(),
    'description': 'Monthly salary or wages',
  },
  {
    'id': 2,
    'name': 'Freelance',
    'type': 'income',
    'icon': Icons.work_outline.codePoint,
    'color': Colors.blue.toARGB32(),
    'description': 'Income from freelance work',
  },
  {
    'id': 3,
    'name': 'Business',
    'type': 'income',
    'icon': Icons.business.codePoint,
    'color': Colors.purple.toARGB32(),
    'description': 'Income from business activities',
  },
  {
    'id': 4,
    'name': 'Investment',
    'type': 'income',
    'icon': Icons.trending_up.codePoint,
    'color': Colors.orange.toARGB32(),
    'description': 'Income from investments',
  },
  {
    'id': 5,
    'name': 'Gift',
    'type': 'income',
    'icon': Icons.card_giftcard.codePoint,
    'color': Colors.pink.toARGB32(),
    'description': 'Money received as a gift',
  },
  {
    'id': 6,
    'name': 'Bonus',
    'type': 'income',
    'icon': Icons.stars.codePoint,
    'color': Colors.cyan.toARGB32(),
    'description': 'Bonuses and rewards',
  },
  {
    'id': 7,
    'name': 'Other Income',
    'type': 'income',
    'icon': Icons.attach_money.codePoint,
    'color': Colors.blueGrey.toARGB32(),
    'description': 'Other sources of income',
  },

  // =========================
  // EXPENSE
  // =========================
  {
    'id': 8,
    'name': 'Food & Dining',
    'type': 'expense',
    'icon': Icons.restaurant.codePoint,
    'color': Colors.deepOrange.toARGB32(),
    'description': 'Restaurants, meals and food',
  },
  {
    'id': 9,
    'name': 'Transportation',
    'type': 'expense',
    'icon': Icons.directions_car.codePoint,
    'color': Colors.indigo.toARGB32(),
    'description': 'Fuel, taxis, public transportation and commuting',
  },
  {
    'id': 10,
    'name': 'Shopping',
    'type': 'expense',
    'icon': Icons.shopping_cart.codePoint,
    'color': Colors.pink.toARGB32(),
    'description': 'Clothes, electronics and other shopping',
  },
  {
    'id': 11,
    'name': 'Bills & Utilities',
    'type': 'expense',
    'icon': Icons.receipt_long.codePoint,
    'color': Colors.brown.toARGB32(),
    'description': 'Electricity, water, gas, internet and bills',
  },
  {
    'id': 12,
    'name': 'Rent',
    'type': 'expense',
    'icon': Icons.home.codePoint,
    'color': Colors.deepPurple.toARGB32(),
    'description': 'House or apartment rent',
  },
  {
    'id': 13,
    'name': 'Healthcare',
    'type': 'expense',
    'icon': Icons.local_hospital.codePoint,
    'color': Colors.red.toARGB32(),
    'description': 'Medical expenses, medicine and healthcare',
  },
  {
    'id': 14,
    'name': 'Entertainment',
    'type': 'expense',
    'icon': Icons.movie.codePoint,
    'color': Colors.purple.toARGB32(),
    'description': 'Movies, games and entertainment',
  },
  {
    'id': 15,
    'name': 'Education',
    'type': 'expense',
    'icon': Icons.school.codePoint,
    'color': Colors.teal.toARGB32(),
    'description': 'Courses, books and education',
  },
  {
    'id': 16,
    'name': 'Subscriptions',
    'type': 'expense',
    'icon': Icons.subscriptions.codePoint,
    'color': Colors.orange.toARGB32(),
    'description': 'Monthly and yearly subscriptions',
  },
  {
    'id': 17,
    'name': 'Travel',
    'type': 'expense',
    'icon': Icons.flight.codePoint,
    'color': Colors.lightBlue.toARGB32(),
    'description': 'Trips, hotels and travel expenses',
  },
  {
    'id': 18,
    'name': 'Personal Care',
    'type': 'expense',
    'icon': Icons.spa.codePoint,
    'color': Colors.lightGreen.toARGB32(),
    'description': 'Haircuts, grooming and personal care',
  },
  {
    'id': 19,
    'name': 'Gifts & Donations',
    'type': 'expense',
    'icon': Icons.volunteer_activism.codePoint,
    'color': Colors.pink.toARGB32(),
    'description': 'Gifts, donations and charitable expenses',
  },
  {
    'id': 20,
    'name': 'Other Expense',
    'type': 'expense',
    'icon': Icons.more_horiz.codePoint,
    'color': Colors.blueGrey.toARGB32(),
    'description': 'Other expenses',
  },
];

final trans = [
  {
    "userId": 1,
    "accountId": 1,
    "categoryId": 3,
    "type": "transfer",
    "amount": 9000,
  },
  {
    "userId": 1,
    "accountId": 1,
    "categoryId": 4,
    "type": "income",
    "amount": 3200,
  },
  {
    "userId": 1,
    "accountId": 1,
    "categoryId": 7,
    "type": "transfer",
    "amount": 4560.50,
  },
  {
    "userId": 1,
    "accountId": 1,
    "categoryId": 6,
    "type": "income",
    "amount": 2530,
  },
  {
    "userId": 1,
    "accountId": 1,
    "categoryId": 9,
    "type": "expense",
    "amount": 450,
  },
  {
    "userId": 1,
    "accountId": 1,
    "categoryId": 10,
    "type": "expense",
    "amount": 630,
  },
  {
    "userId": 1,
    "accountId": 1,
    "categoryId": 11,
    "type": "income",
    "amount": 1250,
  },
  {
    "userId": 1,
    "accountId": 1,
    "categoryId": 12,
    "type": "transfer",
    "amount": 3600,
  },
  {
    "userId": 1,
    "accountId": 1,
    "categoryId": 13,
    "type": "income",
    "amount": 1850,
  },
  {
    "userId": 1,
    "accountId": 1,
    "categoryId": 14,
    "type": "expense",
    "amount": 230,
  },
  {
    "userId": 1,
    "accountId": 1,
    "categoryId": 15,
    "type": "transfer",
    "amount": 2300,
  },
  {
    "userId": 1,
    "accountId": 1,
    "categoryId": 16,
    "type": "income",
    "amount": 1500,
  },
  {
    "userId": 1,
    "accountId": 1,
    "categoryId": 17,
    "type": "expense",
    "amount": 142,
  }
];
